apiVersion: imaversionindeployentyaml
kind: Deployment
metadata:
  name: hello-node-name-from-yaml
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node-kube-docker-image-container
        image: hello-node-kube-docker-image:v1
        ports:
        - containerPort: 8080
