apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: multi-containers-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: multi-containers-deployment
    spec:
      containers:
      - name: drbhello
        image: registry.ng.bluemix.net/drbnamespace/drbhello:drbtag
        ports:
        - containerPort: 8080
      - name: drbapp2
        image: registry.ng.bluemix.net/drbnamespace/drbapp2:drbtag
        ports:
        - containerPort: 8081
