apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: multi-containers-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: multi-containers-deployment
    spec:
      containers:
      - name: hello-container
        image: hello:v1
        ports:
        - containerPort: 8080
      - name: app2-container
        image: app2:v1
        ports:
        - containerPort: 8081
