apiVersion: apps/v1
kind: Deployment
metadata:
  name: help-multi-containers-deployment
spec:
  replicas: {{.Values.numReplicas}}
  template:
    metadata:
      labels:
        app: label-helm-multi-containers-deployment
    spec:
      containers:
      - name: hello-container
        image: 'nginx:latest'
        ports:
        - containerPort: {{.Values.helloPort}}
      - name: app2-container
        image: 'nginx:latest'
        ports:
        - containerPort: {{.Values.app2Port}}
